
   `undef AHB_DATA_WIDTH
   `undef AHB_LITE
   `undef AHB_MASK_PRIORITY
   `undef BUSY
   `undef BYTE
   `undef DWORD
   `undef ERROR
   `undef FALSE
   `undef HADDR_WIDTH
   `undef HBURST_WIDTH
   `undef HMASTER_WIDTH
   `undef HPROT_WIDTH
   `undef HRESP_WIDTH
   `undef HSIZE_WIDTH
   `undef HSPLIT_WIDTH
   `undef HTRANS_WIDTH
   `undef HWORD
   `undef ICM_BUSP_WIDTH
   `undef ICM_BUS_DATA_WIDTH
   `undef ICM_BUS_HADDR_WIDTH
   `undef ICM_BUS_HBURST_WIDTH
   `undef ICM_BUS_HMASTER_WIDTH
   `undef ICM_BUS_HPROT_WIDTH
   `undef ICM_BUS_HSIZE_WIDTH
   `undef ICM_BUS_HTRANS_WIDTH
   `undef ICM_BUS_MID_WIDTH
   `undef ICM_BUS_NUM_HSEL
   `undef ICM_DP_PWIDTH
   `undef ICM_HAS_BURST
   `undef ICM_HAS_LAYER3
   `undef ICM_HAS_LOCK
   `undef ICM_HAS_MHSEL
   `undef ICM_HAS_PROT
   `undef ICM_HAS_SPLIT
   `undef ICM_HAS_UNIQUEP
   `undef ICM_HAS_XPRIORITY
   `undef ICM_HV_HAS_BURST_3
   `undef ICM_HV_HAS_BURST_4
   `undef ICM_HV_HAS_LOCK_3
   `undef ICM_HV_HAS_LOCK_4
   `undef ICM_HV_HAS_MASTER_1
   `undef ICM_HV_HAS_MASTER_2
   `undef ICM_HV_HAS_MASTER_3
   `undef ICM_HV_HAS_MASTER_4
   `undef ICM_HV_HAS_PROT_3
   `undef ICM_HV_HAS_PROT_4
   `undef ICM_LAYERP_WIDTH
   `undef ICM_LAYER_EIGHT_NUM
   `undef ICM_LAYER_ELEVEN_NUM
   `undef ICM_LAYER_FIFTEEN_NUM
   `undef ICM_LAYER_FIVE_NUM
   `undef ICM_LAYER_FOURTEEN_NUM
   `undef ICM_LAYER_FOUR_NUM
   `undef ICM_LAYER_NINE_NUM
   `undef ICM_LAYER_ONE_NUM
   `undef ICM_LAYER_SEVEN_NUM
   `undef ICM_LAYER_SIXTEEN_NUM
   `undef ICM_LAYER_SIX_NUM
   `undef ICM_LAYER_TEN_NUM
   `undef ICM_LAYER_THIRTEEN_NUM
   `undef ICM_LAYER_THREE_NUM
   `undef ICM_LAYER_TWELVE_NUM
   `undef ICM_LAYER_TWO_NUM
   `undef ICM_LAYER_WIDTH
   `undef ICM_MAXP_WIDTH
   `undef ICM_MAX_BUS_DATA_WIDTH
   `undef ICM_MAX_BUS_HADDR_WIDTH
   `undef ICM_MAX_BUS_HBURST_WIDTH
   `undef ICM_MAX_BUS_HMASTER_WIDTH
   `undef ICM_MAX_BUS_HPROT_WIDTH
   `undef ICM_MAX_BUS_HSIZE_WIDTH
   `undef ICM_MAX_BUS_HTRANS_WIDTH
   `undef ICM_MAX_BUS_NUM_HSEL
   `undef ICM_MAX_HSEL
   `undef ICM_MAX_LAYERS
   `undef ICM_NUM_HSEL
   `undef ICM_NUM_LAYERS
   `undef ICM_PRIORITIES_CHANGEABLE
   `undef ICM_PRIORITY_L1
   `undef ICM_PRIORITY_L10
   `undef ICM_PRIORITY_L11
   `undef ICM_PRIORITY_L12
   `undef ICM_PRIORITY_L13
   `undef ICM_PRIORITY_L14
   `undef ICM_PRIORITY_L15
   `undef ICM_PRIORITY_L16
   `undef ICM_PRIORITY_L2
   `undef ICM_PRIORITY_L3
   `undef ICM_PRIORITY_L4
   `undef ICM_PRIORITY_L5
   `undef ICM_PRIORITY_L6
   `undef ICM_PRIORITY_L7
   `undef ICM_PRIORITY_L8
   `undef ICM_PRIORITY_L9
   `undef ICM_PRIORITY_WIDTH
   `undef ICM_RAND_SEED
   `undef ICM_RELEASE_L1
   `undef ICM_RELEASE_L10
   `undef ICM_RELEASE_L11
   `undef ICM_RELEASE_L12
   `undef ICM_RELEASE_L13
   `undef ICM_RELEASE_L14
   `undef ICM_RELEASE_L15
   `undef ICM_RELEASE_L16
   `undef ICM_RELEASE_L2
   `undef ICM_RELEASE_L3
   `undef ICM_RELEASE_L4
   `undef ICM_RELEASE_L5
   `undef ICM_RELEASE_L6
   `undef ICM_RELEASE_L7
   `undef ICM_RELEASE_L8
   `undef ICM_RELEASE_L9
   `undef ICM_RLIMIT_L1
   `undef ICM_RLIMIT_L10
   `undef ICM_RLIMIT_L11
   `undef ICM_RLIMIT_L12
   `undef ICM_RLIMIT_L13
   `undef ICM_RLIMIT_L14
   `undef ICM_RLIMIT_L15
   `undef ICM_RLIMIT_L16
   `undef ICM_RLIMIT_L2
   `undef ICM_RLIMIT_L3
   `undef ICM_RLIMIT_L4
   `undef ICM_RLIMIT_L5
   `undef ICM_RLIMIT_L6
   `undef ICM_RLIMIT_L7
   `undef ICM_RLIMIT_L8
   `undef ICM_RLIMIT_L9
   `undef ICM_RWIDTH_L1
   `undef ICM_RWIDTH_L10
   `undef ICM_RWIDTH_L11
   `undef ICM_RWIDTH_L12
   `undef ICM_RWIDTH_L13
   `undef ICM_RWIDTH_L14
   `undef ICM_RWIDTH_L15
   `undef ICM_RWIDTH_L16
   `undef ICM_RWIDTH_L2
   `undef ICM_RWIDTH_L3
   `undef ICM_RWIDTH_L4
   `undef ICM_RWIDTH_L5
   `undef ICM_RWIDTH_L6
   `undef ICM_RWIDTH_L7
   `undef ICM_RWIDTH_L8
   `undef ICM_RWIDTH_L9
   `undef IDLE
   `undef INCR
   `undef INCR16
   `undef INCR4
   `undef INCR8
   `undef KBYTE
   `undef LOG2_ICM_NUM_LAYERS
   `undef LOG2_ICM_NUM_LAYERS_P1
   `undef LWORD
   `undef MID_LAYNO_WIDTH
   `undef MID_WIDTH
   `undef NONSEQ
   `undef OKAY
   `undef READ
   `undef RETRY
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM05_ATV
   `undef RM_BCM06
   `undef RM_BCM06_ATV
   `undef RM_BCM07
   `undef RM_BCM07_ATV
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_ATV
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM22_ATV
   `undef RM_BCM23
   `undef RM_BCM23_ATV
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM25_ATV
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_AA
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_ATV
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM95_E
   `undef RM_BCM95_I
   `undef RM_BCM95_IE
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_BVM01
   `undef RM_BVM02
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
   `undef SEQ
   `undef SINGLE
   `undef SPLIT
   `undef TRUE
   `undef USE_FOUNDATION
   `undef WORD
   `undef WORD16
   `undef WORD4
   `undef WORD8
   `undef WRAP16
   `undef WRAP4
   `undef WRAP8
   `undef WRITE
   `undef zero16
   `undef zero32
   `undef zero8
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
