// This file was automatically generated by coreAssembler (version N-2017.12-SP5).
// 
// ABSTRACT : SystemVerilog top-level subsystem RTL.
// 

module ahb_3to1 (
    // Ports for Interface HCLK
    input           HCLK_hclk,
    // Ports for Interface HRESETn
    input           HRESETn_hresetn,
    // Ports for Interface ex_i_ahb_1_AHB_Master
    input   [31:0]  ex_i_ahb_1_AHB_Master_haddr,
    input   [2:0]   ex_i_ahb_1_AHB_Master_hburst,
    input           ex_i_ahb_1_AHB_Master_hlock,
    input   [3:0]   ex_i_ahb_1_AHB_Master_hprot,
    input   [2:0]   ex_i_ahb_1_AHB_Master_hsize,
    input   [1:0]   ex_i_ahb_1_AHB_Master_htrans,
    input   [63:0]  ex_i_ahb_1_AHB_Master_hwdata,
    input           ex_i_ahb_1_AHB_Master_hwrite,
    output  [63:0]  ex_i_ahb_1_AHB_Master_hrdata,
    output          ex_i_ahb_1_AHB_Master_hready,
    output  [1:0]   ex_i_ahb_1_AHB_Master_hresp,
    // Ports for Interface ex_i_ahb_2_AHB_Master
    input   [31:0]  ex_i_ahb_2_AHB_Master_haddr,
    input   [2:0]   ex_i_ahb_2_AHB_Master_hburst,
    input           ex_i_ahb_2_AHB_Master_hlock,
    input   [3:0]   ex_i_ahb_2_AHB_Master_hprot,
    input   [2:0]   ex_i_ahb_2_AHB_Master_hsize,
    input   [1:0]   ex_i_ahb_2_AHB_Master_htrans,
    input   [63:0]  ex_i_ahb_2_AHB_Master_hwdata,
    input           ex_i_ahb_2_AHB_Master_hwrite,
    output  [63:0]  ex_i_ahb_2_AHB_Master_hrdata,
    output          ex_i_ahb_2_AHB_Master_hready,
    output  [1:0]   ex_i_ahb_2_AHB_Master_hresp,
    // Ports for Interface ex_i_ahb_AHB_Master
    input   [31:0]  ex_i_ahb_AHB_Master_haddr,
    input   [2:0]   ex_i_ahb_AHB_Master_hburst,
    input           ex_i_ahb_AHB_Master_hlock,
    input   [3:0]   ex_i_ahb_AHB_Master_hprot,
    input   [2:0]   ex_i_ahb_AHB_Master_hsize,
    input   [1:0]   ex_i_ahb_AHB_Master_htrans,
    input   [63:0]  ex_i_ahb_AHB_Master_hwdata,
    input           ex_i_ahb_AHB_Master_hwrite,
    output  [63:0]  ex_i_ahb_AHB_Master_hrdata,
    output          ex_i_ahb_AHB_Master_hready,
    output  [1:0]   ex_i_ahb_AHB_Master_hresp,
    // Ports for Interface ex_i_icm_AHB_Slave
    input   [63:0]  ex_i_icm_AHB_Slave_hrdata,
    input           ex_i_icm_AHB_Slave_hready_resp,
    input   [1:0]   ex_i_icm_AHB_Slave_hresp,
    output  [31:0]  ex_i_icm_AHB_Slave_haddr,
    output  [2:0]   ex_i_icm_AHB_Slave_hburst,
    output          ex_i_icm_AHB_Slave_hmastlock,
    output  [3:0]   ex_i_icm_AHB_Slave_hprot,
    output          ex_i_icm_AHB_Slave_hready,
    output          ex_i_icm_AHB_Slave_hsel,
    output  [2:0]   ex_i_icm_AHB_Slave_hsize,
    output  [1:0]   ex_i_icm_AHB_Slave_htrans,
    output  [63:0]  ex_i_icm_AHB_Slave_hwdata,
    output          ex_i_icm_AHB_Slave_hwrite,
    // Ports for Manually exported pins
    output  [3:0]   i_ahb_1_hmaster_data,
    output  [3:0]   i_ahb_2_hmaster_data,
    output  [3:0]   i_ahb_hmaster_data
);

   wire [31:0]  i_ahb_1_haddr;
   wire [2:0]   i_ahb_1_hburst;
   wire         i_ahb_1_hmastlock;
   wire [3:0]   i_ahb_1_hprot;
   wire         i_ahb_1_hready;
   wire         i_ahb_1_hsel_s1;
   wire [2:0]   i_ahb_1_hsize;
   wire [1:0]   i_ahb_1_htrans;
   wire [63:0]  i_ahb_1_hwdata;
   wire         i_ahb_1_hwrite;
   wire [31:0]  i_ahb_2_haddr;
   wire [2:0]   i_ahb_2_hburst;
   wire         i_ahb_2_hmastlock;
   wire [3:0]   i_ahb_2_hprot;
   wire         i_ahb_2_hready;
   wire         i_ahb_2_hsel_s1;
   wire [2:0]   i_ahb_2_hsize;
   wire [1:0]   i_ahb_2_htrans;
   wire [63:0]  i_ahb_2_hwdata;
   wire         i_ahb_2_hwrite;
   wire [31:0]  i_ahb_haddr;
   wire [2:0]   i_ahb_hburst;
   wire         i_ahb_hmastlock;
   wire [3:0]   i_ahb_hprot;
   wire         i_ahb_hready;
   wire         i_ahb_hsel_s1;
   wire [2:0]   i_ahb_hsize;
   wire [1:0]   i_ahb_htrans;
   wire [63:0]  i_ahb_hwdata;
   wire         i_ahb_hwrite;
   wire [63:0]  i_icm_hrdata_l1;
   wire [63:0]  i_icm_hrdata_l2;
   wire [63:0]  i_icm_hrdata_l3;
   wire         i_icm_hready_resp_l1;
   wire         i_icm_hready_resp_l2;
   wire         i_icm_hready_resp_l3;
   wire [1:0]   i_icm_hresp_l1;
   wire [1:0]   i_icm_hresp_l2;
   wire [1:0]   i_icm_hresp_l3;

   i_ahb_DW_ahb i_ahb
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .haddr_m1       (ex_i_ahb_AHB_Master_haddr),
       .hburst_m1      (ex_i_ahb_AHB_Master_hburst),
       .hlock_m1       (ex_i_ahb_AHB_Master_hlock),
       .hprot_m1       (ex_i_ahb_AHB_Master_hprot),
       .hsize_m1       (ex_i_ahb_AHB_Master_hsize),
       .htrans_m1      (ex_i_ahb_AHB_Master_htrans),
       .hwdata_m1      (ex_i_ahb_AHB_Master_hwdata),
       .hwrite_m1      (ex_i_ahb_AHB_Master_hwrite),
       .hsel_s1        (i_ahb_hsel_s1),
       .hready_resp_s1 (i_icm_hready_resp_l1),
       .hresp_s1       (i_icm_hresp_l1),
       .hrdata_s1      (i_icm_hrdata_l1),
       .haddr          (i_ahb_haddr),
       .hburst         (i_ahb_hburst),
       .hprot          (i_ahb_hprot),
       .hsize          (i_ahb_hsize),
       .htrans         (i_ahb_htrans),
       .hwdata         (i_ahb_hwdata),
       .hwrite         (i_ahb_hwrite),
       .hready         (i_ahb_hready),
       .hresp          (ex_i_ahb_AHB_Master_hresp),
       .hrdata         (ex_i_ahb_AHB_Master_hrdata),
       .hmaster        (),
       .hmaster_data   (i_ahb_hmaster_data),
       .hmastlock      (i_ahb_hmastlock));

   i_ahb_1_DW_ahb i_ahb_1
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .haddr_m1       (ex_i_ahb_1_AHB_Master_haddr),
       .hburst_m1      (ex_i_ahb_1_AHB_Master_hburst),
       .hlock_m1       (ex_i_ahb_1_AHB_Master_hlock),
       .hprot_m1       (ex_i_ahb_1_AHB_Master_hprot),
       .hsize_m1       (ex_i_ahb_1_AHB_Master_hsize),
       .htrans_m1      (ex_i_ahb_1_AHB_Master_htrans),
       .hwdata_m1      (ex_i_ahb_1_AHB_Master_hwdata),
       .hwrite_m1      (ex_i_ahb_1_AHB_Master_hwrite),
       .hsel_s1        (i_ahb_1_hsel_s1),
       .hready_resp_s1 (i_icm_hready_resp_l2),
       .hresp_s1       (i_icm_hresp_l2),
       .hrdata_s1      (i_icm_hrdata_l2),
       .haddr          (i_ahb_1_haddr),
       .hburst         (i_ahb_1_hburst),
       .hprot          (i_ahb_1_hprot),
       .hsize          (i_ahb_1_hsize),
       .htrans         (i_ahb_1_htrans),
       .hwdata         (i_ahb_1_hwdata),
       .hwrite         (i_ahb_1_hwrite),
       .hready         (i_ahb_1_hready),
       .hresp          (ex_i_ahb_1_AHB_Master_hresp),
       .hrdata         (ex_i_ahb_1_AHB_Master_hrdata),
       .hmaster        (),
       .hmaster_data   (i_ahb_1_hmaster_data),
       .hmastlock      (i_ahb_1_hmastlock));

   i_ahb_2_DW_ahb i_ahb_2
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .haddr_m1       (ex_i_ahb_2_AHB_Master_haddr),
       .hburst_m1      (ex_i_ahb_2_AHB_Master_hburst),
       .hlock_m1       (ex_i_ahb_2_AHB_Master_hlock),
       .hprot_m1       (ex_i_ahb_2_AHB_Master_hprot),
       .hsize_m1       (ex_i_ahb_2_AHB_Master_hsize),
       .htrans_m1      (ex_i_ahb_2_AHB_Master_htrans),
       .hwdata_m1      (ex_i_ahb_2_AHB_Master_hwdata),
       .hwrite_m1      (ex_i_ahb_2_AHB_Master_hwrite),
       .hsel_s1        (i_ahb_2_hsel_s1),
       .hready_resp_s1 (i_icm_hready_resp_l3),
       .hresp_s1       (i_icm_hresp_l3),
       .hrdata_s1      (i_icm_hrdata_l3),
       .haddr          (i_ahb_2_haddr),
       .hburst         (i_ahb_2_hburst),
       .hprot          (i_ahb_2_hprot),
       .hsize          (i_ahb_2_hsize),
       .htrans         (i_ahb_2_htrans),
       .hwdata         (i_ahb_2_hwdata),
       .hwrite         (i_ahb_2_hwrite),
       .hready         (i_ahb_2_hready),
       .hresp          (ex_i_ahb_2_AHB_Master_hresp),
       .hrdata         (ex_i_ahb_2_AHB_Master_hrdata),
       .hmaster        (),
       .hmaster_data   (i_ahb_2_hmaster_data),
       .hmastlock      (i_ahb_2_hmastlock));

   i_icm_DW_ahb_icm i_icm
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .hresp          (ex_i_icm_AHB_Slave_hresp),
       .hready_resp    (ex_i_icm_AHB_Slave_hready_resp),
       .hrdata         (ex_i_icm_AHB_Slave_hrdata),
       .hsel_s1_l1     (i_ahb_hsel_s1),
       .haddr_l1       (i_ahb_haddr),
       .htrans_l1      (i_ahb_htrans),
       .hsize_l1       (i_ahb_hsize),
       .hburst_l1      (i_ahb_hburst),
       .hwdata_l1      (i_ahb_hwdata),
       .hwrite_l1      (i_ahb_hwrite),
       .hmastlock_l1   (i_ahb_hmastlock),
       .hprot_l1       (i_ahb_hprot),
       .hready_l1      (i_ahb_hready),
       .hsel_s1_l2     (i_ahb_1_hsel_s1),
       .haddr_l2       (i_ahb_1_haddr),
       .htrans_l2      (i_ahb_1_htrans),
       .hsize_l2       (i_ahb_1_hsize),
       .hburst_l2      (i_ahb_1_hburst),
       .hwdata_l2      (i_ahb_1_hwdata),
       .hwrite_l2      (i_ahb_1_hwrite),
       .hmastlock_l2   (i_ahb_1_hmastlock),
       .hprot_l2       (i_ahb_1_hprot),
       .hready_l2      (i_ahb_1_hready),
       .hsel_s1_l3     (i_ahb_2_hsel_s1),
       .haddr_l3       (i_ahb_2_haddr),
       .htrans_l3      (i_ahb_2_htrans),
       .hsize_l3       (i_ahb_2_hsize),
       .hburst_l3      (i_ahb_2_hburst),
       .hwdata_l3      (i_ahb_2_hwdata),
       .hwrite_l3      (i_ahb_2_hwrite),
       .hmastlock_l3   (i_ahb_2_hmastlock),
       .hprot_l3       (i_ahb_2_hprot),
       .hready_l3      (i_ahb_2_hready),
       .hresp_l1       (i_icm_hresp_l1),
       .hready_resp_l1 (i_icm_hready_resp_l1),
       .hrdata_l1      (i_icm_hrdata_l1),
       .hresp_l2       (i_icm_hresp_l2),
       .hready_resp_l2 (i_icm_hready_resp_l2),
       .hrdata_l2      (i_icm_hrdata_l2),
       .hresp_l3       (i_icm_hresp_l3),
       .hready_resp_l3 (i_icm_hready_resp_l3),
       .hrdata_l3      (i_icm_hrdata_l3),
       .hsel_s1        (ex_i_icm_AHB_Slave_hsel),
       .haddr          (ex_i_icm_AHB_Slave_haddr),
       .htrans         (ex_i_icm_AHB_Slave_htrans),
       .hsize          (ex_i_icm_AHB_Slave_hsize),
       .hburst         (ex_i_icm_AHB_Slave_hburst),
       .hwdata         (ex_i_icm_AHB_Slave_hwdata),
       .hwrite         (ex_i_icm_AHB_Slave_hwrite),
       .hmastlock      (ex_i_icm_AHB_Slave_hmastlock),
       .hprot          (ex_i_icm_AHB_Slave_hprot),
       .hready         (ex_i_icm_AHB_Slave_hready));

   assign ex_i_ahb_1_AHB_Master_hready = i_ahb_1_hready;
   assign ex_i_ahb_2_AHB_Master_hready = i_ahb_2_hready;
   assign ex_i_ahb_AHB_Master_hready = i_ahb_hready;


endmodule
