
   `undef AHB_ADDR_LEM_WIDTH
   `undef AHB_ADDR_MUX_WIDTH
   `undef AHB_CCLM10_OFFSET
   `undef AHB_CCLM11_OFFSET
   `undef AHB_CCLM12_OFFSET
   `undef AHB_CCLM13_OFFSET
   `undef AHB_CCLM14_OFFSET
   `undef AHB_CCLM15_OFFSET
   `undef AHB_CCLM1_OFFSET
   `undef AHB_CCLM2_OFFSET
   `undef AHB_CCLM3_OFFSET
   `undef AHB_CCLM4_OFFSET
   `undef AHB_CCLM5_OFFSET
   `undef AHB_CCLM6_OFFSET
   `undef AHB_CCLM7_OFFSET
   `undef AHB_CCLM8_OFFSET
   `undef AHB_CCLM9_OFFSET
   `undef AHB_CCL_BUS_WIDTH
   `undef AHB_CCL_WIDTH
   `undef AHB_CL_M1
   `undef AHB_CL_M10
   `undef AHB_CL_M11
   `undef AHB_CL_M12
   `undef AHB_CL_M13
   `undef AHB_CL_M14
   `undef AHB_CL_M15
   `undef AHB_CL_M2
   `undef AHB_CL_M3
   `undef AHB_CL_M4
   `undef AHB_CL_M5
   `undef AHB_CL_M6
   `undef AHB_CL_M7
   `undef AHB_CL_M8
   `undef AHB_CL_M9
   `undef AHB_DATA_WIDTH
   `undef AHB_DELAYED_PAUSE
   `undef AHB_FULL_INCR
   `undef AHB_HAS_ARBIF
   `undef AHB_HAS_SPLIT
   `undef AHB_HAS_XDCDR
   `undef AHB_HC_TOKENS
   `undef AHB_LITE
   `undef AHB_LITE_EDEF
   `undef AHB_MAX_ARBIF_WIDTH
   `undef AHB_REQGNT_ONLY_M1
   `undef AHB_REQGNT_ONLY_M10
   `undef AHB_REQGNT_ONLY_M11
   `undef AHB_REQGNT_ONLY_M12
   `undef AHB_REQGNT_ONLY_M13
   `undef AHB_REQGNT_ONLY_M14
   `undef AHB_REQGNT_ONLY_M15
   `undef AHB_REQGNT_ONLY_M2
   `undef AHB_REQGNT_ONLY_M3
   `undef AHB_REQGNT_ONLY_M4
   `undef AHB_REQGNT_ONLY_M5
   `undef AHB_REQGNT_ONLY_M6
   `undef AHB_REQGNT_ONLY_M7
   `undef AHB_REQGNT_ONLY_M8
   `undef AHB_REQGNT_ONLY_M9
   `undef AHB_SINGLE_CYCLE_ARBITRATION
   `undef AHB_TCL
   `undef AHB_TCL_OFFSET
   `undef AHB_TCL_WIDTH
   `undef AHB_TPS_MODE
   `undef AHB_VERSION_ID
   `undef AHB_VID_OFFSET
   `undef AHB_WTEN
   `undef AHB_WTEN_DEBUG
   `undef AHB_WTEN_OFFSET
   `undef AHB_XENDIAN
   `undef ALIAS_M1
   `undef ALIAS_M10
   `undef ALIAS_M11
   `undef ALIAS_M12
   `undef ALIAS_M13
   `undef ALIAS_M14
   `undef ALIAS_M15
   `undef ALIAS_M2
   `undef ALIAS_M3
   `undef ALIAS_M4
   `undef ALIAS_M5
   `undef ALIAS_M6
   `undef ALIAS_M7
   `undef ALIAS_M8
   `undef ALIAS_M9
   `undef ALIAS_S0
   `undef ALIAS_S1
   `undef ALIAS_S10
   `undef ALIAS_S11
   `undef ALIAS_S12
   `undef ALIAS_S13
   `undef ALIAS_S14
   `undef ALIAS_S15
   `undef ALIAS_S16
   `undef ALIAS_S17
   `undef ALIAS_S18
   `undef ALIAS_S19
   `undef ALIAS_S2
   `undef ALIAS_S20
   `undef ALIAS_S21
   `undef ALIAS_S22
   `undef ALIAS_S23
   `undef ALIAS_S24
   `undef ALIAS_S25
   `undef ALIAS_S26
   `undef ALIAS_S27
   `undef ALIAS_S28
   `undef ALIAS_S29
   `undef ALIAS_S3
   `undef ALIAS_S30
   `undef ALIAS_S31
   `undef ALIAS_S4
   `undef ALIAS_S5
   `undef ALIAS_S6
   `undef ALIAS_S7
   `undef ALIAS_S8
   `undef ALIAS_S9
   `undef BIG_ENDIAN
   `undef BUSY
   `undef BUS_AHB_CCL_WIDTH
   `undef BYTE
   `undef C_B_NP_D
   `undef C_B_NP_O
   `undef C_B_P_D
   `undef C_B_P_O
   `undef C_NB_NP_D
   `undef C_NB_NP_O
   `undef C_NP_P_D
   `undef C_NP_P_O
   `undef DFLT_MASTER_OFFSET
   `undef DFLT_MSTR_NUM
   `undef DWORD
   `undef EBTCOUNT_OFFSET
   `undef EBTEN
   `undef EBT_EN_OFFSET
   `undef EBT_OFFSET
   `undef ERROR
   `undef FALSE
   `undef GEN_HSEL0
   `undef HADDR_WIDTH
   `undef HBURSTBUS_WIDTH
   `undef HBURST_WIDTH
   `undef HC_DFLT_MSTR
   `undef HC_PRIORITIES
   `undef HMASTER_WIDTH
   `undef HPROTBUS_WIDTH
   `undef HPROT_WIDTH
   `undef HREADY_WIDTH
   `undef HRESPBUS_WIDTH
   `undef HRESP_WIDTH
   `undef HSEL_ONLY_S0
   `undef HSEL_ONLY_S1
   `undef HSEL_ONLY_S10
   `undef HSEL_ONLY_S11
   `undef HSEL_ONLY_S12
   `undef HSEL_ONLY_S13
   `undef HSEL_ONLY_S14
   `undef HSEL_ONLY_S15
   `undef HSEL_ONLY_S16
   `undef HSEL_ONLY_S17
   `undef HSEL_ONLY_S18
   `undef HSEL_ONLY_S19
   `undef HSEL_ONLY_S2
   `undef HSEL_ONLY_S20
   `undef HSEL_ONLY_S21
   `undef HSEL_ONLY_S22
   `undef HSEL_ONLY_S23
   `undef HSEL_ONLY_S24
   `undef HSEL_ONLY_S25
   `undef HSEL_ONLY_S26
   `undef HSEL_ONLY_S27
   `undef HSEL_ONLY_S28
   `undef HSEL_ONLY_S29
   `undef HSEL_ONLY_S3
   `undef HSEL_ONLY_S30
   `undef HSEL_ONLY_S31
   `undef HSEL_ONLY_S4
   `undef HSEL_ONLY_S5
   `undef HSEL_ONLY_S6
   `undef HSEL_ONLY_S7
   `undef HSEL_ONLY_S8
   `undef HSEL_ONLY_S9
   `undef HSIZEBUS_WIDTH
   `undef HSIZE_WIDTH
   `undef HSPLIT_BUSWIDTH
   `undef HSPLIT_WIDTH
   `undef HTRANSBUS_WIDTH
   `undef HTRANS_WIDTH
   `undef HWORD
   `undef HWRITEBUS_WIDTH
   `undef IDLE
   `undef INCR
   `undef INCR16
   `undef INCR4
   `undef INCR8
   `undef INTERNAL_HSEL
   `undef KBYTE
   `undef LOG2_NUM_INT_MASTERS
   `undef LWORD
   `undef MID_WIDTH
   `undef MR_B1
   `undef MR_B10
   `undef MR_B11
   `undef MR_B12
   `undef MR_B13
   `undef MR_B14
   `undef MR_B15
   `undef MR_B16
   `undef MR_B17
   `undef MR_B18
   `undef MR_B19
   `undef MR_B2
   `undef MR_B20
   `undef MR_B21
   `undef MR_B22
   `undef MR_B23
   `undef MR_B24
   `undef MR_B25
   `undef MR_B26
   `undef MR_B27
   `undef MR_B28
   `undef MR_B29
   `undef MR_B3
   `undef MR_B30
   `undef MR_B31
   `undef MR_B4
   `undef MR_B5
   `undef MR_B6
   `undef MR_B7
   `undef MR_B8
   `undef MR_B9
   `undef MR_N1
   `undef MR_N10
   `undef MR_N11
   `undef MR_N12
   `undef MR_N13
   `undef MR_N14
   `undef MR_N15
   `undef MR_N16
   `undef MR_N17
   `undef MR_N18
   `undef MR_N19
   `undef MR_N2
   `undef MR_N20
   `undef MR_N21
   `undef MR_N22
   `undef MR_N23
   `undef MR_N24
   `undef MR_N25
   `undef MR_N26
   `undef MR_N27
   `undef MR_N28
   `undef MR_N29
   `undef MR_N3
   `undef MR_N30
   `undef MR_N31
   `undef MR_N4
   `undef MR_N5
   `undef MR_N6
   `undef MR_N7
   `undef MR_N8
   `undef MR_N9
   `undef NC_B_NP_D
   `undef NC_B_NP_O
   `undef NC_B_P_D
   `undef NC_B_P_O
   `undef NC_NB_NP_D
   `undef NC_NB_NP_O
   `undef NC_NB_P_D
   `undef NC_NB_P_O
   `undef NONSEQ
   `undef NUM_AHB_MASTERS
   `undef NUM_BAHB_SLAVES
   `undef NUM_IAHB_SLAVES
   `undef NUM_INT_MASTERS
   `undef NUM_INT_SLAVES
   `undef NUM_NAHB_SLAVES
   `undef OKAY
   `undef PAUSE
   `undef PL10_OFFSET
   `undef PL11_OFFSET
   `undef PL12_OFFSET
   `undef PL13_OFFSET
   `undef PL14_OFFSET
   `undef PL15_OFFSET
   `undef PL1_OFFSET
   `undef PL2_OFFSET
   `undef PL3_OFFSET
   `undef PL4_OFFSET
   `undef PL5_OFFSET
   `undef PL6_OFFSET
   `undef PL7_OFFSET
   `undef PL8_OFFSET
   `undef PL9_OFFSET
   `undef PRIORITY_1
   `undef PRIORITY_10
   `undef PRIORITY_11
   `undef PRIORITY_12
   `undef PRIORITY_13
   `undef PRIORITY_14
   `undef PRIORITY_15
   `undef PRIORITY_2
   `undef PRIORITY_3
   `undef PRIORITY_4
   `undef PRIORITY_5
   `undef PRIORITY_6
   `undef PRIORITY_7
   `undef PRIORITY_8
   `undef PRIORITY_9
   `undef R1_B_EA_0
   `undef R1_B_EA_1
   `undef R1_B_EA_10
   `undef R1_B_EA_11
   `undef R1_B_EA_12
   `undef R1_B_EA_13
   `undef R1_B_EA_14
   `undef R1_B_EA_15
   `undef R1_B_EA_16
   `undef R1_B_EA_17
   `undef R1_B_EA_18
   `undef R1_B_EA_19
   `undef R1_B_EA_2
   `undef R1_B_EA_20
   `undef R1_B_EA_21
   `undef R1_B_EA_22
   `undef R1_B_EA_23
   `undef R1_B_EA_24
   `undef R1_B_EA_25
   `undef R1_B_EA_26
   `undef R1_B_EA_27
   `undef R1_B_EA_28
   `undef R1_B_EA_29
   `undef R1_B_EA_3
   `undef R1_B_EA_30
   `undef R1_B_EA_31
   `undef R1_B_EA_4
   `undef R1_B_EA_5
   `undef R1_B_EA_6
   `undef R1_B_EA_7
   `undef R1_B_EA_8
   `undef R1_B_EA_9
   `undef R1_B_SA_0
   `undef R1_B_SA_1
   `undef R1_B_SA_10
   `undef R1_B_SA_11
   `undef R1_B_SA_12
   `undef R1_B_SA_13
   `undef R1_B_SA_14
   `undef R1_B_SA_15
   `undef R1_B_SA_16
   `undef R1_B_SA_17
   `undef R1_B_SA_18
   `undef R1_B_SA_19
   `undef R1_B_SA_2
   `undef R1_B_SA_20
   `undef R1_B_SA_21
   `undef R1_B_SA_22
   `undef R1_B_SA_23
   `undef R1_B_SA_24
   `undef R1_B_SA_25
   `undef R1_B_SA_26
   `undef R1_B_SA_27
   `undef R1_B_SA_28
   `undef R1_B_SA_29
   `undef R1_B_SA_3
   `undef R1_B_SA_30
   `undef R1_B_SA_31
   `undef R1_B_SA_4
   `undef R1_B_SA_5
   `undef R1_B_SA_6
   `undef R1_B_SA_7
   `undef R1_B_SA_8
   `undef R1_B_SA_9
   `undef R1_N_EA_0
   `undef R1_N_EA_1
   `undef R1_N_EA_10
   `undef R1_N_EA_11
   `undef R1_N_EA_12
   `undef R1_N_EA_13
   `undef R1_N_EA_14
   `undef R1_N_EA_15
   `undef R1_N_EA_16
   `undef R1_N_EA_17
   `undef R1_N_EA_18
   `undef R1_N_EA_19
   `undef R1_N_EA_2
   `undef R1_N_EA_20
   `undef R1_N_EA_21
   `undef R1_N_EA_22
   `undef R1_N_EA_23
   `undef R1_N_EA_24
   `undef R1_N_EA_25
   `undef R1_N_EA_26
   `undef R1_N_EA_27
   `undef R1_N_EA_28
   `undef R1_N_EA_29
   `undef R1_N_EA_3
   `undef R1_N_EA_30
   `undef R1_N_EA_31
   `undef R1_N_EA_4
   `undef R1_N_EA_5
   `undef R1_N_EA_6
   `undef R1_N_EA_7
   `undef R1_N_EA_8
   `undef R1_N_EA_9
   `undef R1_N_SA_0
   `undef R1_N_SA_1
   `undef R1_N_SA_10
   `undef R1_N_SA_11
   `undef R1_N_SA_12
   `undef R1_N_SA_13
   `undef R1_N_SA_14
   `undef R1_N_SA_15
   `undef R1_N_SA_16
   `undef R1_N_SA_17
   `undef R1_N_SA_18
   `undef R1_N_SA_19
   `undef R1_N_SA_2
   `undef R1_N_SA_20
   `undef R1_N_SA_21
   `undef R1_N_SA_22
   `undef R1_N_SA_23
   `undef R1_N_SA_24
   `undef R1_N_SA_25
   `undef R1_N_SA_26
   `undef R1_N_SA_27
   `undef R1_N_SA_28
   `undef R1_N_SA_29
   `undef R1_N_SA_3
   `undef R1_N_SA_30
   `undef R1_N_SA_31
   `undef R1_N_SA_4
   `undef R1_N_SA_5
   `undef R1_N_SA_6
   `undef R1_N_SA_7
   `undef R1_N_SA_8
   `undef R1_N_SA_9
   `undef R2_B_EA_1
   `undef R2_B_EA_10
   `undef R2_B_EA_11
   `undef R2_B_EA_12
   `undef R2_B_EA_13
   `undef R2_B_EA_14
   `undef R2_B_EA_15
   `undef R2_B_EA_16
   `undef R2_B_EA_17
   `undef R2_B_EA_18
   `undef R2_B_EA_19
   `undef R2_B_EA_2
   `undef R2_B_EA_20
   `undef R2_B_EA_21
   `undef R2_B_EA_22
   `undef R2_B_EA_23
   `undef R2_B_EA_24
   `undef R2_B_EA_25
   `undef R2_B_EA_26
   `undef R2_B_EA_27
   `undef R2_B_EA_28
   `undef R2_B_EA_29
   `undef R2_B_EA_3
   `undef R2_B_EA_30
   `undef R2_B_EA_31
   `undef R2_B_EA_4
   `undef R2_B_EA_5
   `undef R2_B_EA_6
   `undef R2_B_EA_7
   `undef R2_B_EA_8
   `undef R2_B_EA_9
   `undef R2_B_SA_1
   `undef R2_B_SA_10
   `undef R2_B_SA_11
   `undef R2_B_SA_12
   `undef R2_B_SA_13
   `undef R2_B_SA_14
   `undef R2_B_SA_15
   `undef R2_B_SA_16
   `undef R2_B_SA_17
   `undef R2_B_SA_18
   `undef R2_B_SA_19
   `undef R2_B_SA_2
   `undef R2_B_SA_20
   `undef R2_B_SA_21
   `undef R2_B_SA_22
   `undef R2_B_SA_23
   `undef R2_B_SA_24
   `undef R2_B_SA_25
   `undef R2_B_SA_26
   `undef R2_B_SA_27
   `undef R2_B_SA_28
   `undef R2_B_SA_29
   `undef R2_B_SA_3
   `undef R2_B_SA_30
   `undef R2_B_SA_31
   `undef R2_B_SA_4
   `undef R2_B_SA_5
   `undef R2_B_SA_6
   `undef R2_B_SA_7
   `undef R2_B_SA_8
   `undef R2_B_SA_9
   `undef R2_N_EA_1
   `undef R2_N_EA_10
   `undef R2_N_EA_11
   `undef R2_N_EA_12
   `undef R2_N_EA_13
   `undef R2_N_EA_14
   `undef R2_N_EA_15
   `undef R2_N_EA_16
   `undef R2_N_EA_17
   `undef R2_N_EA_18
   `undef R2_N_EA_19
   `undef R2_N_EA_2
   `undef R2_N_EA_20
   `undef R2_N_EA_21
   `undef R2_N_EA_22
   `undef R2_N_EA_23
   `undef R2_N_EA_24
   `undef R2_N_EA_25
   `undef R2_N_EA_26
   `undef R2_N_EA_27
   `undef R2_N_EA_28
   `undef R2_N_EA_29
   `undef R2_N_EA_3
   `undef R2_N_EA_30
   `undef R2_N_EA_31
   `undef R2_N_EA_4
   `undef R2_N_EA_5
   `undef R2_N_EA_6
   `undef R2_N_EA_7
   `undef R2_N_EA_8
   `undef R2_N_EA_9
   `undef R2_N_SA_1
   `undef R2_N_SA_10
   `undef R2_N_SA_11
   `undef R2_N_SA_12
   `undef R2_N_SA_13
   `undef R2_N_SA_14
   `undef R2_N_SA_15
   `undef R2_N_SA_16
   `undef R2_N_SA_17
   `undef R2_N_SA_18
   `undef R2_N_SA_19
   `undef R2_N_SA_2
   `undef R2_N_SA_20
   `undef R2_N_SA_21
   `undef R2_N_SA_22
   `undef R2_N_SA_23
   `undef R2_N_SA_24
   `undef R2_N_SA_25
   `undef R2_N_SA_26
   `undef R2_N_SA_27
   `undef R2_N_SA_28
   `undef R2_N_SA_29
   `undef R2_N_SA_3
   `undef R2_N_SA_30
   `undef R2_N_SA_31
   `undef R2_N_SA_4
   `undef R2_N_SA_5
   `undef R2_N_SA_6
   `undef R2_N_SA_7
   `undef R2_N_SA_8
   `undef R2_N_SA_9
   `undef R3_B_EA_1
   `undef R3_B_SA_1
   `undef R3_N_EA_1
   `undef R3_N_SA_1
   `undef R4_B_EA_1
   `undef R4_B_SA_1
   `undef R4_N_EA_1
   `undef R4_N_SA_1
   `undef R5_B_EA_1
   `undef R5_B_SA_1
   `undef R5_N_EA_1
   `undef R5_N_SA_1
   `undef R6_B_EA_1
   `undef R6_B_SA_1
   `undef R6_N_EA_1
   `undef R6_N_SA_1
   `undef R7_B_EA_1
   `undef R7_B_SA_1
   `undef R7_N_EA_1
   `undef R7_N_SA_1
   `undef R8_B_EA_1
   `undef R8_B_SA_1
   `undef R8_N_EA_1
   `undef R8_N_SA_1
   `undef READ
   `undef REMAP
   `undef RETRY
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM05_ATV
   `undef RM_BCM06
   `undef RM_BCM06_ATV
   `undef RM_BCM07
   `undef RM_BCM07_ATV
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_ATV
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM22_ATV
   `undef RM_BCM23
   `undef RM_BCM23_ATV
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM25_ATV
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_AA
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_ATV
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM95_E
   `undef RM_BCM95_I
   `undef RM_BCM95_IE
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_BVM01
   `undef RM_BVM02
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
   `undef SEQ
   `undef SINGLE
   `undef SPLIT
   `undef SPLITBUS_WIDTH
   `undef SPLIT_CAPABLE_0
   `undef SPLIT_CAPABLE_1
   `undef SPLIT_CAPABLE_10
   `undef SPLIT_CAPABLE_11
   `undef SPLIT_CAPABLE_12
   `undef SPLIT_CAPABLE_13
   `undef SPLIT_CAPABLE_14
   `undef SPLIT_CAPABLE_15
   `undef SPLIT_CAPABLE_16
   `undef SPLIT_CAPABLE_17
   `undef SPLIT_CAPABLE_18
   `undef SPLIT_CAPABLE_19
   `undef SPLIT_CAPABLE_2
   `undef SPLIT_CAPABLE_20
   `undef SPLIT_CAPABLE_21
   `undef SPLIT_CAPABLE_22
   `undef SPLIT_CAPABLE_23
   `undef SPLIT_CAPABLE_24
   `undef SPLIT_CAPABLE_25
   `undef SPLIT_CAPABLE_26
   `undef SPLIT_CAPABLE_27
   `undef SPLIT_CAPABLE_28
   `undef SPLIT_CAPABLE_29
   `undef SPLIT_CAPABLE_3
   `undef SPLIT_CAPABLE_30
   `undef SPLIT_CAPABLE_31
   `undef SPLIT_CAPABLE_4
   `undef SPLIT_CAPABLE_5
   `undef SPLIT_CAPABLE_6
   `undef SPLIT_CAPABLE_7
   `undef SPLIT_CAPABLE_8
   `undef SPLIT_CAPABLE_9
   `undef TRUE
   `undef USE_FOUNDATION
   `undef VISIBLE_0
   `undef VISIBLE_1
   `undef VISIBLE_10
   `undef VISIBLE_11
   `undef VISIBLE_12
   `undef VISIBLE_13
   `undef VISIBLE_14
   `undef VISIBLE_15
   `undef VISIBLE_16
   `undef VISIBLE_17
   `undef VISIBLE_18
   `undef VISIBLE_19
   `undef VISIBLE_2
   `undef VISIBLE_20
   `undef VISIBLE_21
   `undef VISIBLE_22
   `undef VISIBLE_23
   `undef VISIBLE_24
   `undef VISIBLE_25
   `undef VISIBLE_26
   `undef VISIBLE_27
   `undef VISIBLE_28
   `undef VISIBLE_29
   `undef VISIBLE_3
   `undef VISIBLE_30
   `undef VISIBLE_31
   `undef VISIBLE_4
   `undef VISIBLE_5
   `undef VISIBLE_6
   `undef VISIBLE_7
   `undef VISIBLE_8
   `undef VISIBLE_9
   `undef WORD
   `undef WORD16
   `undef WORD4
   `undef WORD8
   `undef WRAP16
   `undef WRAP4
   `undef WRAP8
   `undef WRITE
   `undef XDCDR_SUPPLIES_HSELS2AHB
   `undef zero16
   `undef zero32
   `undef zero8
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
